//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcptunGUI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class 字符串 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal 字符串() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KcptunGUI.Resource.字符串", typeof(字符串).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;Language&quot;:&quot;简体中文&quot;,&quot;LangTag&quot;:&quot;zh_CN&quot;,&quot;LCID&quot;:2052,&quot;Text&quot;:[&quot;KcptunGUI&quot;,&quot;客户端&quot;,&quot;服务端&quot;,&quot;首选项&quot;,&quot;状态&quot;,&quot;关于&quot;,&quot;显示当前运行状态&quot;,&quot;关于本程序&quot;,&quot;进行首选项设定&quot;,&quot;客户端模式&quot;,&quot;服务端模式&quot;,&quot;处理器占用&quot;,&quot;内存占用&quot;,&quot;网络占用&quot;,&quot;系统上传速率:&quot;,&quot;系统下载速率:&quot;,&quot;系统CPU负载:&quot;,&quot;程序CPU占用:&quot;,&quot;系统内存占用:&quot;,&quot;程序共享内存占用:&quot;,&quot;程序真实内存占用:&quot;,&quot;以下选项会即时生效并自动保存&quot;,&quot;是否自动关闭导航菜单&quot;,&quot;是否记住窗口位置&quot;,&quot;是否读取系统状态&quot;,&quot;区域ID,程序会根据区域提供不同的全球化内容&quot;,&quot;程序显示语言&quot;,&quot;退出&quot;]} 的本地化字符串。
        /// </summary>
        public static string String_Language_CHS {
            get {
                return ResourceManager.GetString("String_Language_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;Language&quot;:&quot;简体中文&quot;,&quot;LangTag&quot;:&quot;zh_CN&quot;,&quot;LCID&quot;:2052,&quot;Text&quot;:[&quot;KcptunGUI&quot;,&quot;客户端&quot;,&quot;服务端&quot;,&quot;首选项&quot;,&quot;状态&quot;,&quot;关于&quot;,&quot;显示当前运行状态&quot;,&quot;关于本程序&quot;,&quot;进行首选项设定&quot;,&quot;客户端模式&quot;,&quot;服务端模式&quot;,&quot;处理器占用&quot;,&quot;内存占用&quot;,&quot;网络占用&quot;,&quot;系统上传速率:&quot;,&quot;系统下载速率:&quot;,&quot;系统CPU负载:&quot;,&quot;程序CPU占用:&quot;,&quot;系统内存占用:&quot;,&quot;程序共享内存占用:&quot;,&quot;程序真实内存占用:&quot;,&quot;以下选项会即时生效并自动保存&quot;,&quot;是否自动关闭导航菜单&quot;,&quot;是否记住窗口位置&quot;,&quot;是否读取系统状态&quot;,&quot;区域ID,程序会根据区域提供不同的全球化内容&quot;,&quot;程序显示语言&quot;,&quot;退出&quot;]} 的本地化字符串。
        /// </summary>
        public static string String_Language_ENG {
            get {
                return ResourceManager.GetString("String_Language_ENG", resourceCulture);
            }
        }
    }
}
