//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcptunGUI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class 字符串 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal 字符串() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KcptunGUI.Resource.字符串", typeof(字符串).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;Language&quot;:&quot;简体中文&quot;,&quot;LangTag&quot;:&quot;zh_CN&quot;,&quot;LCID&quot;:2052,&quot;Text&quot;:[&quot;KcptunGUI&quot;,&quot;客户端&quot;,&quot;服务端&quot;,&quot;首选项&quot;,&quot;状态&quot;,&quot;关于&quot;,&quot;显示当前运行状态&quot;,&quot;关于本程序&quot;,&quot;进行首选项设定&quot;,&quot;客户端模式&quot;,&quot;服务端模式&quot;,&quot;以下选项会即时生效并自动保存&quot;,&quot;是否自动关闭导航菜单&quot;,&quot;是否记住窗口位置&quot;,&quot;是否读取系统状态&quot;,&quot;区域ID,据此提供不同的内容&quot;,&quot;程序显示语言&quot;,&quot;处理器&quot;,&quot;处理器负载:&quot;,&quot;程序处理器占用:&quot;,&quot;内存&quot;,&quot;内存负载:&quot;,&quot;程序占用:&quot;,&quot;网络&quot;,&quot;系统上传速率:&quot;,&quot;系统下载速率:&quot;,&quot;KcptunGUI总出网速率:&quot;,&quot;KcptunGUI总入网速率:&quot;,&quot;Kcptun总出网速率:&quot;,&quot;Kcptun总入网速率:&quot;,&quot;有效流量比:&quot;,&quot;退出&quot;]} 的本地化字符串。
        /// </summary>
        public static string String_Language_CHS {
            get {
                return ResourceManager.GetString("String_Language_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;Language&quot;:&quot;English&quot;,&quot;LangTag&quot;:&quot;en_us&quot;,&quot;LCID&quot;:1033,&quot;Text&quot;:[&quot;KcptunGUI&quot;,&quot;Client&quot;,&quot;Server&quot;,&quot;Config&quot;,&quot;Status&quot;,&quot;About&quot;,&quot;Display application status&quot;,&quot;About application&quot;,&quot;Configure settings&quot;,&quot;Client mode&quot;,&quot;Server mode&quot;,&quot;These settings will apply immediately&quot;,&quot;Whether or not auto close menu&quot;,&quot;Whether or not remember window location&quot;,&quot;Whether or not fetch application status&quot;,&quot;Location ID&quot;,&quot;Applocation display language&quot;,&quot;Processor&quot;,&quot;Processor load:&quot;,&quot;Application occupied:&quot;,&quot;Memory&quot;,&quot;System occupied:&quot;,&quot;Application o [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string String_Language_ENG {
            get {
                return ResourceManager.GetString("String_Language_ENG", resourceCulture);
            }
        }
    }
}
