//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcptunGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KcptunGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon_favicon_ico {
            get {
                object obj = ResourceManager.GetObject("icon_favicon_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap picture_favicon_png {
            get {
                object obj = ResourceManager.GetObject("picture_favicon_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;LCID&quot;:2052,&quot;TabAutoHide&quot;:false,&quot;RememberWinLocation&quot;:false,&quot;WinLocation&quot;:[0,0],&quot;Nodes&quot;:[{&quot;hostname&quot;:&quot;too.simple.com&quot;,&quot;ip&quot;:&quot;1.2.4.8&quot;,&quot;description&quot;:&quot;图样主机 - 1&quot;,&quot;localport&quot;:1081,&quot;remoteport&quot;:8000,&quot;autoconnect&quot;:false}]} 的本地化字符串。
        /// </summary>
        internal static string String_AppConfigJsonDefault {
            get {
                return ResourceManager.GetString("String_AppConfigJsonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;LCID&quot;:{&quot;type&quot;:&quot;integer&quot;},&quot;TabAutoHide&quot;:{&quot;type&quot;:&quot;boolean&quot;},&quot;RememberWinLocation&quot;:{&quot;type&quot;:&quot;boolean&quot;},&quot;WinLocation&quot;:{&quot;type&quot;:&quot;array&quot;,&quot;items&quot;:{&quot;type&quot;:&quot;integer&quot;}},&quot;Nodes&quot;:{&quot;type&quot;:&quot;array&quot;,&quot;items&quot;:{&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;hostname&quot;:{&quot;type&quot;:&quot;string&quot;},&quot;ip&quot;:{&quot;type&quot;:&quot;string&quot;},&quot;description&quot;:{&quot;type&quot;:&quot;string&quot;},&quot;localport&quot;:{&quot;type&quot;:&quot;integer&quot;},&quot;remoteport&quot;:{&quot;type&quot;:&quot;integer&quot;},&quot;autoconnect&quot;:{&quot;type&quot;:&quot;boolean&quot;}},&quot;required&quot;:[&quot;hostname&quot;,&quot;ip&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String_AppConfigJsonSchema {
            get {
                return ResourceManager.GetString("String_AppConfigJsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;Language&quot;:&quot;简体中文&quot;,&quot;LangTag&quot;:&quot;zh_CN&quot;,&quot;LCID&quot;:2052,&quot;Text&quot;:[&quot;客户端&quot;,&quot;服务端&quot;,&quot;首选项&quot;,&quot;关于&quot;,&quot;状态&quot;,&quot;帮助&quot;,&quot;显示当前运行状态&quot;,&quot;获得使用帮助&quot;,&quot;关于本程序&quot;,&quot;进行首选项设定&quot;,&quot;处理器占用&quot;,&quot;内存占用&quot;,&quot;网络占用&quot;]} 的本地化字符串。
        /// </summary>
        internal static string String_AppLanguageJsonDefault {
            get {
                return ResourceManager.GetString("String_AppLanguageJsonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;$schema&quot;:&quot;http://json-schema.org/draft-04/schema#&quot;,&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;Language&quot;:{&quot;type&quot;:&quot;string&quot;},&quot;LangTag&quot;:{&quot;type&quot;:&quot;string&quot;},&quot;LCID&quot;:{&quot;type&quot;:&quot;integer&quot;},&quot;Text&quot;:{&quot;type&quot;:&quot;array&quot;,&quot;items&quot;:{&quot;type&quot;:&quot;string&quot;}}},&quot;required&quot;:[&quot;Language&quot;,&quot;LangTag&quot;,&quot;LCID&quot;,&quot;Text&quot;]} 的本地化字符串。
        /// </summary>
        internal static string String_AppLanguageJsonSchema {
            get {
                return ResourceManager.GetString("String_AppLanguageJsonSchema", resourceCulture);
            }
        }
    }
}
